name=input("Enter the name")
dob=int(input("enter date of birth in the form of ddmmyy"))
organisation=input(("enter the organisation name"))
contact=int(input("enter your contact no"))
emailid=int(input("enter email address"))
print("Name",name)
print("Organisation",organisation)
print("Contact",contact)
print("DOB",dob)
print("emailid",emailid)