f=open("D:\filehandling.txt","w")
f.write("My college is PSIT")
f.close()
f=open("D:\filehandling.txt","r")
print(f.read())
f.close()
f=open("D:\filehandling.txt","a")
f.write("now the file has more content")
f.close()
f=open("D:\filehandling","r")
print(f.read())
f.close()